name       : kodi
version    : 15.2
release    : 3
source     :
    - https://github.com/xbmc/xbmc/archive/15.2-Isengard.tar.gz : dd8aeb942e6de5d1488e243e1346cff3f6597e21b5131a3ba72ff5cc82037110
license    : GPL-2.0
summary    : Kodi Media Hub
description: |
    Kodi is an award-winning free and open source (GPL) software media player and entertainment hub for digital media.
builddeps  :
    - alsa-utils
    - fontconfig
    - freetype2
    - git
    - jasper-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - libmad-devel
    - lzo-devel
    - openjdk-8
    - swig
    - pkgconfig(alsa)
    - pkgconfig(gnutls)
    - pkgconfig(libxslt)
    - pkgconfig(fribidi)
    - pkgconfig(libmpeg2)
    - pkgconfig(samplerate)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(flac)
    - pkgconfig(libtiff-4)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(sqlite3)
    - pkgconfig(sdl2)
    - pkgconfig(libbluray)
    - pkgconfig(SDL2_image)
    - pkgconfig(tinyxml)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(libass)
    - pkgconfig(libcdio)
    - pkgconfig(taglib)
    - pkgconfig(libmodplug)
    - pkgconfig(wayland-client)
    - pkgconfig(yajl)
    - pkgconfig(zlib)
    - libiconv-devel
    - libiconv
setup      : |
    sh bootstrap
    CFLAGS="-Wc99-c11-compat" CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11" PCRECPP_LIBS="-L/usr/local/lib -lpcrecpp" LDFLAGS="-L/usr/local/lib" ./configure --prefix=/usr/local --with-gnu-ld --disable-ccache --disable-debug --disable-dvdcss --disable-joystick --disable-samba --disable-mysql --disable-optical-drive
build      : |
    %make
install    : |
    %make_install
