name       : kodi
version    : 15.2
release    : 3
source     :
    - https://github.com/xbmc/xbmc/archive/15.2-Isengard.tar.gz : dd8aeb942e6de5d1488e243e1346cff3f6597e21b5131a3ba72ff5cc82037110
license    : GPL-2.0
summary    : Kodi Media Hub
description: |
    Kodi is an award-winning free and open source (GPL) software media player and entertainment hub for digital media.
builddeps  :
    - alsa-utils
    - fontconfig
    - freetype2
    - gperf
    - hicolor-icon-theme
    - jasper-devel
    - libboost-devel
    - libiconv
    - libiconv-devel
    - libjpeg-turbo-devel
    - libmad-devel
    - lzo-devel
    - nasm
    - openjdk-8
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(gnutls)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio)
    - pkgconfig(libcec)
#    - pkgconfig(libgl)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libpcre)
    - pkgconfig(libplist)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(librtmp)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(ogg)
    - pkgconfig(samplerate)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(smbclient)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(tinyxml)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
    - pkgconfig(yajl)
    - pkgconfig(zlib)
    - python-pillow
    - swig
setup      : |
    sh bootstrap
    CFLAGS="-Wc99-c11-compat" CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11" PCRECPP_LIBS="-L/usr/local/lib -lpcrecpp" LDFLAGS="-L/usr/local/lib" ./configure --prefix=/usr/local --with-gnu-ld --disable-ccache --disable-debug --disable-dvdcss --disable-joystick --disable-samba --disable-mysql --disable-optical-drive
build      : |
    %make
install    : |
    %make_install
