name       : kodi
version    : 17.3
release    : 23
source     :
    - https://github.com/xbmc/xbmc/archive/17.3-Krypton.tar.gz : 1de8653a3729cefd1baaf09ecde5ace01a1e3a58fbf29d48c1363f2503d331a1
license    : GPL-2.0
component  : desktop.multimedia
summary    : Free and open source software media center
description: |
    Kodi® (formerly known as XBMC™) is an award-winning free and open source (GPL) software media center for playing videos, music, pictures, games, and more.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(bluez)
    - pkgconfig(dbus-1)
    - pkgconfig(glu)
    - pkgconfig(gnutls)
    - pkgconfig(lcms2)
    - pkgconfig(libass)
    - pkgconfig(libavformat)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio)
    - pkgconfig(libcec)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libnfs)
    - pkgconfig(libplist)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(libzip)
    - pkgconfig(smbclient)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(tinyxml)
    - pkgconfig(vdpau)
    - pkgconfig(xrandr)
    - pkgconfig(yajl)
    - crossguid-devel
    - giflib-devel
    - git
    - gperf
    - libunistring-devel
    - lzo-devel
    - openjdk-8-devel
    - shairplay-devel
    - swig
rundeps    :
    - shairplay
setup      : |
    # WARN: Do NOT enable binutils-gold, even if kodi prefers it
    #   --  binutils-gold makes ffmpeg barf on gnutls during ./configure

    mkdir kodi-build
    cd kodi-build

    # TODO: Enable and test lirc support (infrared remote)
    #       and add e.g. -DLIRC_DEVICE=/run/lirc/lircd \
    #

    %cmake ../project/cmake \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=%libdir% \
      -DENABLE_EVENTCLIENTS=ON \
      -DENABLE_MYSQLCLIENT=FALSE \

    # INFO: To display available configuration variables and
    #       their detected values, uncomment the following:
    #
    #%cmake ../project/cmake -L | awk '{if(f)print} /-- Cache values/{f=1}'
    #fail_for_inspection  # stop the build here for inspection

build      : |
    cd kodi-build

    # noiser cmake build for troubleshooting purposes
    #cmake --build . -- VERBOSE=1

    %make

install    : |
    cd kodi-build

    %make_install
