name       : kodi
version    : 15.1
release    : 2
source     :
    - https://github.com/xbmc/xbmc/archive/15.1-Isengard.tar.gz : 72b2610d8fbff807128d74429f25bf6716ba880c27c2c5d9fad012ec7fc70705
license    : GPL-2.0
summary    : Kodi Media Hub
description: |
    Kodi is an award-winning free and open source (GPL) software media player and entertainment hub for digital media.
builddeps  :
    - alsa-utils
    - fontconfig
    - freetype2
    - git
    - jasper-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - libmad-devel
    - lzo
    - openjdk-8
    - swig
    - pkgconfig(alsa)
    - pkgconfig(gnutls)
    - pkgconfig(libxslt)
    - pkgconfig(fribidi)
    - pkgconfig(libmpeg2)
    - pkgconfig(samplerate)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(flac)
    - pkgconfig(libtiff-4)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(sqlite3)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(libass)
    - pkgconfig(libcdio)
    - pkgconfig(taglib)
    - pkgconfig(libmodplug)
    - pkgconfig(wayland-client)
    - pkgconfig(yajl)
setup      : |
    MAKEFLAGS=-j1 ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
