name       : kodi
version    : 14.2
release    : 1
source     :
    - https://github.com/xbmc/xbmc/archive/14.2-Helix.tar.gz : d9cb8590430a925fb789a5beb4da2695cdcd2d2500dd31126f3b77b31aa267f4
license    : GPL-2.0
summary    : Kodi Media Hub
description: |
    Kodi is an award-winning free and open source (GPL) software media player and entertainment hub for digital media.
clang      : no
builddeps  :
    - alsa-utils
    - fontconfig
    - freetype2
    - git
    - jasper-devel
    - libboost
    - libjpeg-turbo-devel
    - libmad-devel
    - lzo
    - swig
    - pkgconfig(alsa)
    - pkgconfig(gnutls)
    - pkgconfig(libxslt)
    - pkgconfig(fribidi)
    - pkgconfig(libmpeg2)
    - pkgconfig(samplerate)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(flac)
    - pkgconfig(libtiff-4)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(sqlite3)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(libass)
    - pkgconfig(libcdio)
    - pkgconfig(taglib)
    - pkgconfig(libmodplug)
    - pkgconfig(wayland-client)
    - pkgconfig(yajl)
setup      : |
    MAKEFLAGS=-j1 ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
