name       : kodi
version    : 17.0
release    : 6
source     :
    - https://github.com/xbmc/xbmc/archive/17.0b2-Krypton.tar.gz : 18b21769b3921e6d9c18b04c3598a0a21f998cb9664ec4e1a3c97371b1d4adc3
license    : GPL-2.0
component  : desktop.multimedia
summary    : Free and open source software media center
description: |
    Kodi® (formerly known as XBMC™) is an award-winning free and open source (GPL) software media center for playing videos, music, pictures, games, and more.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(openssl)
    - pkgconfig(gnutls)
    - pkgconfig(tinyxml)
    - pkgconfig(uuid)
    - pkgconfig(yajl)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(fribidi)
    - pkgconfig(sqlite3)
    - pkgconfig(libpcrecpp)
    - pkgconfig(libpcre)
    - pkgconfig(freetype2)
    - pkgconfig(taglib)
    - pkgconfig(libcdio)
    - pkgconfig(libzip)
    - pkgconfig(libbluray)
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
    - pkgconfig(libdrm)
    - pkgconfig(egl)
    - pkgconfig(libssh)
    - pkgconfig(smbclient)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libcec)
    - pkgconfig(lcms2)
    - pkgconfig(bluez)
    - pkgconfig(libva)
    - pkgconfig(libavformat)
    - pkgconfig(glu)
    - pkgconfig(libass)
    - pkgconfig(libmicrohttpd)
    - libcap2-devel
    - swig
    - openjdk-8-devel
    - lzo-devel
    - crossguid-devel
    - gperf
    - git
setup      : |
    ./bootstrap

    %configure PREFIX=/usr \
        --enable-libbluray \
        --with-ffmpeg=auto \
        --disable-mysql \
        --enable-static=no \
        --enable-shared=yes
build      : |
    %make
install    : |
    %make_install
