name       : kodi
version    : '20.1'
release    : 85
source     :
    - https://github.com/xbmc/xbmc/archive/refs/tags/20.1-Nexus.tar.gz : cd4158b2bc2d9593ad2f5c1cd2494957ab726b13d8379bbfb09d7d36df7b7d7e
license    : GPL-2.0-or-later
component  : desktop.multimedia
summary    : Free and open source software media center
description: |
    Kodi® (formerly known as XBMC™) is an award-winning free and open source (GPL) software media center for playing videos, music, pictures, games, and more. The Solus Kodi build includes essential binary add-ons and select libretro cores.
networking : yes
optimize   : speed
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(bluez)
    - pkgconfig(dbus-1)
    - pkgconfig(fmt)
    - pkgconfig(fstrcmp)
    - pkgconfig(gbm)
    - pkgconfig(glu)
    - pkgconfig(gtest)
    - pkgconfig(lcms2)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio)
    - pkgconfig(libcec)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libdvdcss)
    - pkgconfig(libjpeg)
    - pkgconfig(liblzma)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libmodplug)
    - pkgconfig(libnfs)
    - pkgconfig(libpcrecpp)
    - pkgconfig(libplist-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(libzip)
    - pkgconfig(lirc)
    - pkgconfig(mariadb)
    - pkgconfig(python3)
    - pkgconfig(smbclient)
    - pkgconfig(spdlog)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(tinyxml)
    - pkgconfig(vdpau)
    - pkgconfig(xrandr)
    - flatbuffers-devel
    - giflib-devel
    - git
    - gperf
    - libunistring-devel
    - lzo-devel
    - openjdk-17-devel
    - shairplay-devel
    - sndio-devel
    - swig
rundeps    :
    - libmodplug
    - libva-intel-driver
    - shairplay
environment: |
    PATH="$PATH:/usr/lib64/openjdk-17/bin/"
setup      : |
    # include kodi retroplayer addons
    # cp -f $pkgfiles/binary-addons.txt %workdir%/cmake/addons/bootstrap/repositories/

    # WARN: Do NOT enable binutils-gold, even if kodi says it prefers it
    #   --  binutils-gold makes the main kodi build fail.
    #

    # Fix up mariadb mysql.h include path
    %patch -p1 < $pkgfiles/mariadb-fix.patch

    mkdir kodi-build && cd kodi-build
    %cmake .. \
      -DADDONS_TO_BUILD="*" \
      -DAPP_RENDER_SYSTEM=gl \
      -DBUILD_SHARED_LIBS=ON \
      -DCORE_PLATFORM_NAME=x11 \
      -DENABLE_AIRTUNES=ON \
      -DENABLE_AVAHI=ON \
      -DENABLE_BLUETOOTH=ON \
      -DENABLE_CEC=ON \
      -DENABLE_EVENTCLIENTS=ON \
      -DENABLE_INTERNAL_CROSSGUID=ON \
      -DENABLE_INTERNAL_FFMPEG=OFF \
      -DENABLE_INTERNAL_FLATBUFFERS=OFF \
      -DENABLE_INTERNAL_FMT=OFF \
      -DENABLE_INTERNAL_FSTRCMP=OFF \
      -DENABLE_INTERNAL_SPDLOG=OFF \
      -DENABLE_INTERNAL_UDFREAD=OFF \
      -DENABLE_LDGOLD=OFF \
      -DENABLE_MARIADBCLIENT=ON \
      -DENABLE_MYSQLCLIENT=OFF \
      -DENABLE_OPTICAL=ON \
      -DENABLE_SMBCLIENT=ON \
      -DENABLE_UPNP=ON \
      -DLIRC_DEVICE=/run/lirc/lircd \
      -DMARIADBCLIENT_INCLUDE_DIR=/usr/include/mysql \
      -DUSE_SHARED_LIB=ON

    # INFO: To display available configuration variables and
    #       their detected values, uncomment the following:
    #
    #cmake .. -L | awk '{if(f)print} /-- Cache values/{f=0}'
    #exit 1  # stop the build here to inspect config options
    #
build      : |
    # main kodi build
    #
    %make -C kodi-build

    # INFO: noiser build for troubleshooting purposes
    #%make VERBOSE=1 -j1 -C kodi-build
    #
install    : |
    # install kodi proper
    #
    %make_install -C kodi-build

    # INFO: The binary addons need to reference installed Kodi software
    #       artifacts.
    #       Since we're building a "batteries included" version
    #       of Kodi in one go, we need to violate the configure/build/install
    #       order here and only configure *after* kodi has been installed to
    #       the CMAKE_INSTALL_PREFIX.
    #
    #       Note that the default binary add-on make target includes all sorts
    #       of fancy dependency fetching/building with vendored libs
    #       plus an install target.
    #
    # INFO: https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#51-in-tree-building-of-binary-add-ons
    %make -C tools/depends/target/binary-addons PREFIX="$installdir/usr"
check      : |
    # INFO: Tests last forever. You can run them locally but please make sure
    #       the commands are commented out before publishing
    #
    #%make check -C kodi-build
